name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign issue creator'
        uses: pozil/auto-assign-issue@v2
        with:
          script: |
            const issue = context.payload.issue;
            const assignee = issue.user.login;
            const { github, context } = require('@actions/github');

            // Assign the issue to the creator
            await github.issues.addAssignees({
              ...context.repo,
              issue_number: issue.number,
              assignees: [assignee],
            });
