name: Auto Assign Issue Creator

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign issue to creator
      uses: kentaro-m/auto-assign-action@v2.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
